### ISSUE TITLE
'build_script' stage will be replaced soon (discuss)

### ISSUE THREAD

**Issue by Lakr233** [cirruslabs/gitlab-tart-executor#80]
I've see log from gitlab shown as:

```
WARNING: Starting with version 17.0 the 'build_script' stage will be replaced with 'step_script': https://gitlab.com/groups/gitlab-org/-/epics/6112
```

Any info or plan about for fixing this?

**Comment by edigaryev** [comment]
GitLab Tart Executor is completely agnostic to [run stages](https://docs.gitlab.com/runner/executors/custom.html#run).

But it seems that in order to disable this warning, we need the GitLab Runner team to move forward with [epic 6112](https://gitlab.com/groups/gitlab-org/-/epics/6112) and particularly [issue 27957](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27957), which will allow the GitLab Tart Executor to communicate this to the GitLab Runner.
