### ISSUE TITLE
Images are always pulled

### ISSUE THREAD

**Issue by spiegelball** [cirruslabs/gitlab-tart-executor#89]
Even with TART_EXECUTOR_ALWAYS_PULL=false set system wide the base image is pulled on every run. How can I investigate why this happens?

**Comment by edigaryev** [comment]
This most likely happens due to [automatic pruning](https://tart.run/faq/#automatic-pruning) in Tart, which removes the VM images from the OCI cache to prevent space shortage.

You can try adding the `"--auto-prune", "false"` to [`--prepare` stage](https://github.com/cirruslabs/gitlab-tart-executor?tab=readme-ov-file#prepare-stage) to disable this mechanism.
